### ISSUE TITLE
Legge om til mkdocs/material tema og scriptbasert byggeprosess

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#121]
Forslaget går ut på å benytte et annet, mye vakrere og mer funksjonelt tema for github.io sidene for best-practice. [Material for Mkdocs](https://squidfunk.github.io/mkdocs-material/) for å være eksakt. Dette temaet har god støtte for extensions og kan blant annet rendre mermaid diagram, noe som er svært praktisk.

Det er ihvertfall en snag og en avgjørelse som må tas:
1. README.md er i dag innholdsfortegnelsen vår, denne ligger i hovedkatalogen. Mkdocs forventer imidlertid en index.md fil som første side av dokumentasjonen og denne skal ligge under *docs* katalogen.
   * Dette betyr at innholdet i README må flyttes og at dette IKKE blir synlig fra forsiden av repoet (det kan selvfølgelig ligge en lenke til den produserte dokumentasjonen i README istedenfor). Se også diskusjon om [dette](https://github.com/mkdocs/mkdocs/issues/321)
4. Vi må bestemme oss for om vi skal bygge io sider hver gang det committes til master eller om vi skal ha mer versjonskontroll og bare bygge når vi vet det er viktige endringer.

**Comment by rockphotog** [comment]
1. Ser ikke dette som problematisk. Og med mkdocs med gode menyer vil innholdet være lettere tilgjengelig, er vel noe automagisk ToC etc. der. 

2. Jeg synes dagens praksis fungerer greit, men man kan være mer påpasselig med hva man pusher til master ved å f.eks. alltid bruke branches. Sidene bør jo være levende og ikke statiske.

**Comment by thomiz** [comment]
Æsj, det var litt mer komplisert enn jeg hadde sett for meg. En testgenerering ga relativt mange feil, brukne lenker og manglende bilder i [resultatet](https://thomiz.github.io/best-practice-material/)

**Comment by rockphotog** [comment]
Kan jo vurdere å teste med en install fra scratch på "roten" til HL7 Norge, altså ikke Best Practice. Så er det kanskje enklere å migrere?

**Comment by oaassv** [comment]
Hei Thomas,
jeg synes sidene ser meget ryddige ut med den nye malen. For meg er det litt forvirrende å følge sammenhengen mellom navigasjonshierarkiet til høyre og forsiden med "Beste praksis" som inneholder en del overlappende tema, men med noe forskjellige overskrifter.

**Comment by thomiz** [comment]
Ja, innholdsoversikten på forsiden er ikke synket med sidemenyen. Bør være en ganske rask jobb. Soørsmålet er om vi skal ha innholdsoversikt på forsiden, eller om vi bare skal ha sidemeny og generell intro på forsiden istedenfor?

**Comment by oaassv** [comment]
Jeg tror kanskje jeg stemmer for en mer generell intro - med fokus på tema som ikke er i parallell i sidemenyen. Men sikkert fint med en diskusjon på det.

**Comment by thomiz** [comment]
Ja, jeg tror også det en generell intro som forside er den modellen som fungerer best. Så får vi ikke dobbelt vedlikehold.
Hva synes du @rockphotog ?
