### ISSUE TITLE
Beskrivelse av prinsipper for nasjonale profiler

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#31]
Fylle ut med informasjon fra beskrivelsen av dette som du finner på sharepoint:
https://sh.ehelse.no/Styring/Standardisering/FHIR/Delte%20dokumenter/FHIR-hierarki_profiler.pptx?Web=1

**Comment by rockphotog** [comment]
I første omgang legger jeg inne en beskrivelse av top down vs bottom up, ref epost fra Nasjonalt senter for e-helseforskning.

**Comment by rockphotog** [comment]
Lukker denne. For the record, førsteutkastet som er presentert i workshop ligger her:

https://github.com/HL7Norway/best-practice/blob/master/docs/no-national-profiles-principles.md
