### ISSUE TITLE
Prinsipp 2: Anvendelsen for basisprofilen er tydelig definert

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/best-practice#35]
_**Den konkrete anvendelsen for basisprofilen må være tydelig definert** og knyttet til samhandling. Anvendelsen må beskrives på et generelt nivå, som gjør det mulig å relatere anvendelsen til de fleste samhandlingsbehov i Norsk helsesektor._

Foreslår at vi skriver om prinsippet, eller kanskje til og med fjerner det. Basisprofiler handler ikke så mye om konkrete anvendelser på samme måte som f.eks. områdeprofiler, så det kan misforstås. 

https://github.com/HL7Norway/best-practice/blob/master/docs/no-basis-principles.md

**Comment by thomiz** [comment]
Jeg mener vi trenger et slik prinsipp også for basisprofiler, men at det er viktig at det ikke blandes med områdeprofiler.

Formålet er å si hva bruker vi denne ressursen til i Norge. Beskrivelsen må være generell nok til å dekke de fleste samhandlingsbehov i norge, i motsetning til områdeprofiler som skal dekke anvendelser innen ett bestemt område. Vi har slike beskrivelser på basisprofilene idag slik som for PractitionerRole:
*The main use-case of no-basis-PractitionerRole is to represent the role or function of a Practitioner wihtin an organization. The resource can include information about services performed by a Practitioner, a location where the practitioner performes the functions as well as information about the nature of the employment at an organization.*

**Comment by rockphotog** [comment]
Grunnen min var at det står _anvendelse = tydelig definert_, samtidig som at basisprofiler ikke lener seg på noe spesifikke anvendelser. Så en slags motsetning.

**Comment by thomiz** [comment]
Hvordan skal man anvende denne ressursen i Norge? Alternativt kan vi benytte en annen term?

**Comment by rockphotog** [comment]
Vi skriver i prinsipp 1 at (...)_som er felles for de fleste anvendelser i Norge_ 

Kanskje prinsipp 2 kunne fortelle at basisprofiler i hovedsak skal benyttes for all videre profilering hvis de finnes - men ordlyden avhenger jo også litt av normeringsnivå som ligger utenfor "scope" for prinsippene.

**Comment by thomiz** [comment]
Forslag til endring @rockphotog @oaassv :

**Prinsipp 2: Anvendelsesområdet for basisprofilen må favne mange brukstilfeller**
Basisprofiler vil som hovedregel være grunnlag for all videre profilering av en FHIR ressurs i Norge. Definisjonen av anvendelsesområdet må derfor være av generell karakter, slik at profilen blir anvendbar for samhandling innen de fleste brukstilfeller nasjonalt.

**Comment by oaassv** [comment]
Prinsipp 2: Basisprofil av en ressurs skal kunne benyttes i de aller fleste anvendelser
Basisprofiler vil som hovedregel være grunnlag for all videre profilering av en FHIR ressurs i Norge. Den bør derfor være så generelle som mulig.

**Comment by thomiz** [comment]
Etter å ha sett på sammenhengen mellom de tre første prinsippene så er det bare definisjonen av den norske konteksten som påvirker basisprofilen vi faktisk trenger å dokumentere i prinsipp 2. Eksempel for PractitionerRole definerer vi konteksten som påvirker profileringsvalgene til å være rollen til en helseperson i en organisasjon. For Organisasjon definerer vi konteksten til å være identifikasjon av organisasjoner som leverer helsetjenester til norsk helsesektor og for Pasient så definerer vi relevant kontekst å være identifikatorsystemer som er relevant for personer og pasienter i Norge samt muligheten for å representere norske navn og adresser.

Siden prinsipp 1 slår fast at basisprofiler beskriver grunnleggende tilpasninger for de fleste anvendelser og prinsipp 3 slår fast at profilen defineres utfra anvendelsen i norsk kontekst så gjenstår det egentlig bare for prinsipp 2 å slå fast at den konteksten som påvirker profilen må dokumenteres.  Foreslår derfor at Prinsipp 2 blir så enkelt som mulig.
**Prinsipp 2: Konteksten som påvirker basisprofilen må være dokumentert**
Den særnorske kontekst som påvirker basisprofilen beskrives i dokumentasjonen av basisprofilen. Dette kan være særnorske krav knyttet til juridiske, organisatorisk, semantisk eller tekniske egenskaper som påvirker struktur og innhold i en spesifikk FHIR ressurs.

Dette betyr også at prinsipp 3 kan kuttes noe ned, siden omfanget av konteksten og krav til dokumentasjon av denne er definert i prinsipp 2.
**Prinsipp 3: Profilene defineres ut fra anvendelse i en norsk kontekst**
Profilene beskrives slik at de tilfredsstiller krav for bruk av FHIR ressursen i Norge. Detaljnivå er avhengig av behovene knyttet til gjenbruk i områdeprofiler og implementerte profiler.

**Comment by rockphotog** [comment]
Burde 80/20-regelen være reflektert i ett av prinsippene, f.eks. kommentar til prinsipp 1 eller knyttet til det Øyvind skriver i sitt forslag til prinsipp 2?

**Comment by thomiz** [comment]
80/20-regelen er vel kanskje en 85/21 regel med hensyn på no-basis? Vi gjør litt ytterligere profilering (altså standardiserer 21%, en 1% utvidelse i forhold til vanillla HL7 FHIR ) for å dekke 85% av brukertilfellene i Norge.

Resten overlates til områdeprofiler og implementerte profiler.

Hva tenker du om å endre prinsipp 2 til å handle mest om konteksten @rockphotog ?

**Comment by rockphotog** [comment]
Kontekst er såvidt nevnt i forklaringen til prinsipp 1 (Norge), men det kan godt ha et eget prinsipp. Støtte norske juridiske og semantiske regler (organisatorisk?) - men ikke tekniske. Definisjon mellomnavn er jo juridisk, mens bruk av et gitt kodeverk kan være bestemt både juridisk, organisatorisk og semantisk (...men semantisk kan kanskje ikke definere seg selv, kravene kommer alltid fra jur/org).

**Comment by thomiz** [comment]
Vi har jo spesifikke tekniske infrastrukturløsninger som kan stille noen krav til teknisk løsning, men det er ikke sikkert de er så relevante på no-basis nivå. Semantiske krav som er særnorske mener jeg vi har flere av, det kan handle om tolkningen av juridiske krav på et semantisk nivå (som for mellomnavn), men det kan også handle om særnorske semantiske strukturer som vi benytter i Norge, eksempel kodeverk og terminologi. Jeg tror uansett det er lurt å tenke på og eventuelt beskrive hvorvidt særnorsk teknisk infrastruktur eller semantikk påvirker basisprofilene på noen måte.

Jeg tenker at : "Basisprofiler skal understøtte norske krav om juridisk, organisatorisk og semantisk samhandlingsevne" er i egentlig en kopi av nye prinsipp 3. Så prinsipp 2 trenger bare beskrive hvilken kontekst vi tenker på og at den skal dokumenteres.

**Comment by rockphotog** [comment]
Kanskje det da holder å justere prinsipp 3, og kutte ut nr 2?

**Comment by thomiz** [comment]
Det er en annen mulighet.

**Comment by thomiz** [comment]
Da er prinsipp 2 slettet: 
*Prinsipp 2: Anvendelsen for basisprofilen er tydelig definert
Den konkrete anvendelsen for basisprofilen må være tydelig definert og knyttet til samhandling. Anvendelsen må beskrives på et generelt nivå, som gjør det mulig å relatere anvendelsen til de fleste samhandlingsbehov i Norsk helsesektor.*

Og Prinsipp 3 har fått krav om dokumentasjon av kontekst: 
*Den norske konteksten skal dokumenteres i profilen.*
