### ISSUE TITLE
Opprette wiki-side for Fagforum FHIR

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/best-practice#39]
Inkludert utkast til mandat. Mandatet kan diskuteres på det første møtet.

**Comment by rockphotog** [comment]
https://github.com/HL7Norway/best-practice/tree/master/docs/fff

**Comment by rockphotog** [comment]
@thomiz Har også begynt, se https://github.com/HL7Norway/best-practice/tree/master/docs/fff (kunne jo ventet med master)

**Comment by thomiz** [comment]
Wikisider er oppe å kjøre. Sjekk ut og fiks skrivefeil osv.
@rockphotog @oaassv

**Comment by rockphotog** [comment]
Vi må jobbe litt med navnet - blir litt tungt/mange F'er :-)

**Comment by rockphotog** [comment]
Skal vi ta mål av oss av vi skrur på tekst etc. - og så begynner å spre budskapet onsdag 2020-10-14 aka "Verdens standardiseringsdag"? @thomiz @oaassv

**Comment by oaassv** [comment]
Hehe, god ide @rockphotog . 

Tenkte vi bør presentere konseptet - og gjerne brainstorme litt på navn - på fagseminaret på tirsdag. Hvis ingen kommer opp med gode navn så får vi eventuelt se om vi greier å finne på noe mer elegang enn FFF selv. Men kult hvis vi kan sende ut første møteinvitasjon på selve standardiseringsdagen.

**Comment by thomiz** [comment]
Lansere FFF 14 bør vi klare.
FHIR fagforum og fagforum FHIR er begge bedre enn FHIR Faglig forum andre forslag:
FHIR rådet
FHIR for fremtiden
FHIR/works
working FHIR

Ble plutselig litt svak for *FHIR/works* , da vet jeg hvordan logoen skal se ut også.

**Comment by thomiz** [comment]
FHIRworks er brukt tidligere, men det virker ikke som noen bruker det aktivt lenger. 
Epic hadde et arrangement i 2015, men ser ikke noe etter det. Også har AWS noe FHIR works on AWS, men det kan neppe forveksles.

**Comment by thomiz** [comment]
Se egen issue om navnevalg
