### ISSUE TITLE
Lage regler navngivning nasjonale profiler

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/best-practice#4]
I dagens eksempler i hierarkiet brukes "std-[Ressurs]", men vi må kanskje ha "no-" først slik som ved basisprofilene. 

[Wiki nasjonale profiler](https://github.com/HL7Norway/best-practice/wiki/Prinsipper-for-nasjonale-profiler)

### Forslag
* no-[Ressursnavn] - Enkelt og greit
* no-std-[Ressursnavn] - For å understreke at dette er standard-profiler

Kjør debatt.

**Comment by rockphotog** [comment]
Siste forslag er at nasjonale områdeprofiler skal begynne med <code>no-domain-</code>.

**Comment by thomiz** [comment]
no-domain- er et godt forslag, kan du sjekk om det kommer i konflikt med noen andre som bruker lignende navngivning @rockphotog ?

**Comment by rockphotog** [comment]
Eller skal vi bruke no-core- så det er mer gjenkjennelig for verden der ute? 

Har ikke funnet noen som bruker "domain", stort sett core, eller rett på navnet på området. 
@thomiz @oaassv

**Comment by oaassv** [comment]
Hei,jeg tror Core kanskje ellers er brukt der vi har brukt basis. 
øyvind
    På fredag 28. august 2020, 10:31:01 CEST skrev Espen Stranger Seland <notifications@github.com> følgende:  
 
 


Eller skal vi bruke no-core- så det er mer gjenkjennelig for verden der ute?

Har ikke funnet noen som bruker "domain", stort sett core, eller rett på navnet på området.
@thomiz @oaassv

**Comment by rockphotog** [comment]
Ja, men vår basis er annerledes en core. Vår basis er særnorske regler, mens core rundt omkring er "minimumsett", dvs inneholder must-support++. Og våre områdeprofiler ser jeg for meg kanskje er hakket strengere i en del tilfeller. Så kanskje no-domain ikke er så dumt likevel?

**Comment by oaassv** [comment]
Jeg synes no-domain er bra - core representerer uansett litt forskjellige ting i ulike land - ex NL vs US.
    På fredag 28. august 2020, 10:57:30 CEST skrev Espen Stranger Seland <notifications@github.com> følgende:  
 
 


Ja, men vår basis er annerledes en core. Vår basis er særnorske regler, mens core rundt omkring er "minimumsett", dvs inneholder must-support++. Og våre områdeprofiler ser jeg for meg kanskje er hakket strengere i en del tilfeller. Så kanskje no-domain ikke er så dumt likevel?

**Comment by thomiz** [comment]
Det eneste er jo at folk gjør narr av "No basis" navnet, de kommer vel til å gjøre narr av "No domain" også? Men det er jo et problem fordi vi har valgt "no" i hovedsak. @rockphotog @oaassv

**Comment by oaassv** [comment]
Vi får flytte til Sverige eller Danmark - de blir ikke gjort narr av pga prefixene sine :)

**Comment by rockphotog** [comment]
Funny name, it is. Lukker.
