### ISSUE TITLE
Definisjon nasjonale områdeprofiler - endre tekst

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/best-practice#40]
Forslag til tekstlig endring fra passiv til aktiv:

Fra: _En områdeprofil **skal representere** informasjonsstrukturer som kan gjenbrukes på tvers av implementasjoner for det definerte anvendelsesområdet._ 

Til: _En områdeprofil **representerer** informasjonsstrukturer som kan gjenbrukes på tvers av implementasjoner for det definerte anvendelsesområdet._

**Comment by thomiz** [comment]
En grei endring, men vi må kanskje ta stilling til om vi SKAL legge oss på "normeringsspråk" med predefinerte "SKAL", "BØR" og "KAN" definisjoner?

**Comment by rockphotog** [comment]
Jeg synes det er et godt forslag. Dette skal tross alt normeres, så definisjon/prinsipper bør følge den malen (som sikkert er en ISO-standard i seg selv).

**Comment by rockphotog** [comment]
RFC som HL7 har pekt på: https://www.ietf.org/rfc/rfc2119.txt 
(ref https://www.hl7.org/FHIR/2015May/conformance-rules.html)

**Comment by thomiz** [comment]
Vi kan vurdere å innføre bruk av SKAL, KAN, BØR i versjon 2.0 (når metoden blir retningslinje).

**Comment by rockphotog** [comment]
Erstattes av issue #90.
