### ISSUE TITLE
Definisjon: Aktiv forvaltning

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/best-practice#42]
Vi trenger en definisjon på hva aktiv forvaltning innebærer, og krav til det. Noen forslag:

- Det MÅ være en profesjonell part (en organisasjon) eller vedvarende interessegruppe (?)
- Den aktive forvalteren MÅ kunne ta i mot endringsønsker/bugs etc og ta de inn (implementere, avvise etc)
- FORESLÅ ovenfor normerende myndighet om ny versjon bør normeres (og evt eldre bør tas ut). 

Se også: https://github.com/HL7Norway/best-practice/blob/develop-den-gode-implementasjonsguide/docs/dgi/index.md#forvaltning-og-kontaktinformasjon

**Comment by rockphotog** [comment]
Tas inn i metode-dokumentet.

**Comment by thomiz** [comment]
Begrepet er endret til "ansvarlig forvalter"
