### ISSUE TITLE
Navnevalg for FHIR fagforum

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#52]
Kom med innspill til navn for FHIR faglig forum. Frist før første møte, senest Onsdag 2020-11-11 klokken 12. Eller stem på eksisterende navneforslag. Bare post en kommentar til denne issue med navneforslag eller det navneforslaget du foretrekker.

- FHIRworks
- FHIR fagforum
- FHIR faglig forum
- fagforum FHIR
- FHIR rådet
- FHIR for fremtiden

**Comment by thomiz** [comment]
Ser ikke ut til å fungere

**Comment by sigskjer** [comment]
Mange gode forslag.
Den første er vel opptatt ("An app to explore the conformance profile of HL7 FHIR systems", https://chrome.google.com/webstore/detail/fhirworks-fhir-client-pac/jkfphagfbfionpiipogdhbmdichcafkh)

Stemmer for det enkle "FHIR fagforum", men kan jo for spøk legge til følgende forslag:
**Brannvakta**
-Sigbjørn

**Comment by rockphotog** [comment]
Godt forslag! Jeg liker uformelle navn, for å påpeke at dette er faglig og uformelt. 
Siden jeg er en ute-mann slenger jeg på noen til:
- Bålplassen
- Leirbål(et)

**Comment by linnbrandt** [comment]
FHIR fagforum (hvorfor gjøre det vanskelig når man kan gjøre det lett:)

**Comment by terjebless** [comment]
Enig med @linnbrandt: "Fagforum" er et innarbeidet begrep for denne typen konstellasjoner. Det finnes f.eks. fagforum for prossessarkitektur, informasjonsarkitektur, og sikkerhetsarkitektur i spesialisthelsetjenesten.

**Comment by thomiz** [comment]
To navneforslag som kom inn under første møte i fagforum:
FHIRvesenet
Helse on FHIR

Kom gjerne med flere forslag eller legg inn din stemme på din foretrukne kandidat.

**Comment by thomiz** [comment]
FHIR fagforum er banket av majoriteten :-)
