### ISSUE TITLE
Shorthand & SUSHI - eksperimentering

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/best-practice#53]
Jeg har begynt å teste Shorthand/SUSHI. Later som jeg skal lage nordisk mellomnavn-ekstension - se egen branch _experimental_. Det er et stykke å gå, det mangler en god del i Shorthand, men jeg tror også vi har unødvendig mye rask i en del av filene våre. 

https://github.com/HL7Norway/best-practice/blob/experimental/sushi/nordic-middlename/fsh/nordic-extension-middlename.fsh

**Comment by rockphotog** [comment]
Generere structurdefinitions er én ting, men Sushi tar seg av IG-mekking med IG Publisher langt enklere enn tidligere.

**Comment by rockphotog** [comment]
Et veldig ungt prosjekt lager verktøy for å gå fra eksisterende definisjoner til FSH:

https://github.com/FHIR/GoFSH

**Comment by thomiz** [comment]
Vi har en arbeidsflyt for dette på trappene.
