### ISSUE TITLE
Forslag til tema FHIR fagforum

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#56]
HL7 FHIR er en standard designet for utveksling av helseinformasjon. Formålet med FFF er å øke kompetansen og dele erfaringer med bruk av standarden HL7 FHIR i Norge. FFF skal fungere som et åpent forum for faglige presentasjoner, erfaringsformidling og åpne diskusjoner knyttet til anvendelse av HL7 FHIR for samhandling.

Kom med forslag til tema/saker som kan tas opp i FHIR faglig forum. Det kan gjerne være et tema hvor du selv kan ha en innledning eller snakke om et faglig tema.

**Comment by thomiz** [comment]
Jeg kunne ønske meg en presentasjon fra SAFEST prosjektet: https://github.com/HL7Norway/SAFEST
Vil gjerne utfordre @stinejohans1 og @rockphotog til å presentere FHIR arbeidet som utføres i prosjektet.

**Comment by ingvarso** [comment]
> Jeg kunne ønske meg en presentasjon fra SAFEST prosjektet: https://github.com/HL7Norway/SAFEST
> Vil gjerne utfordre @stinejohans1 og @rockphotog til å presentere FHIR arbeidet som utføres i prosjektet.

Det vil vi veldig gjerne høre litt om!

**Comment by terjebless** [comment]
FHIR Messaging?

R5?

**Comment by thomiz** [comment]
Presentasjon fra SFM og SAFEST i samme møte? Kan få til noen interessante brytningspunkter kanskje?

**Comment by rockphotog** [comment]
@stinejohans1 Sendte deg en epost! :-)

**Comment by ingvarso** [comment]
FHIR Dokumenter mener jeg er et svært viktig område, som vi burde belyse og diskutere.

**Comment by rockphotog** [comment]
Legger denne her:
https://chat.fhir.org/#narrow/stream/179226-norway/topic/Modell.20for.20nasjonal.20FHIR.20Profilering
@ingvarso @thomiz @oaassv

**Comment by thomiz** [comment]
Terminologi og SNOMED CT er ønsket som tema for fagforum. Dette kan være tema for et møte i 2021. Det arrangeres også et webinar med fokus på SNOMED og felles språk 15 desember. Espen går der igjennom veldig kort status forholdet SNOMED og FHIR.

**Comment by thomiz** [comment]
Vi kunne hatt et tema om forskjellige FHIR implementasjoner som er tilgjengelige og erfaringer med disse. Det er antakelig spesielt serversiden som er interessant. Vi har jo personer og fagmiljøer som har erfaringer med flere servere:
* Vonk
* SmileCDR
* HAPI
* Microsoft FHIR server
* Spark

**Comment by rockphotog** [comment]
> FHIR Messaging?

Jeg vet flere og flere er interessert i messaging, inkludert Helsenorge. Jeg lagde for 2-3 år siden et utkast for å MessageHeader for å kunne erstatte KITH Hodemelding som nå har dukket opp igjen. Vi har en side her, som vi bør oppdatere:

https://github.com/HL7Norway/best-practice/blob/master/docs/messaging.md

**Comment by thomiz** [comment]
Digital hjemmeoppfølging og bruk av CarePlan er det antakelig flere miljøer både i Norge og internasjonalt som arbeider med. Noen som kan presentere?

**Comment by ingvarso** [comment]
Jeg tar gjerne en presentasjon av det vi har gjort i forbindelse med digital egenbehandlingsplan.

**Comment by thomiz** [comment]
Høres veldig bra ut! Kanskje dette passer til neste møte, skal diskutere møteplanen med sekretariatet for fagforum idag.

**Comment by thomiz** [comment]
Forslag fra møtet 2021-01-27 - Questionnaire og SDC (Structured Data Capture)

**Comment by oaassv** [comment]
Presentasjon av rapportering til registre med utgangspunkt i tarmkreftscreeningrapportering til Kreftregisteret i HSØ. Her legges det inn en ekstra innsats i å finne en god generell tilnærming for bruk av FHIR for rapportering til registre, og det er leid inn ekspertise fra Firely i profileringsarbeidet. Kan være interessant å diskutere som en mal for andre registerrapporteringsprosjekter.

**Comment by rockphotog** [comment]
@oaassv Generell metode for for registerrapportering er påbegynt her: 
https://github.com/HL7Norway/innrapportering-helseregister

**Comment by thomiz** [comment]
Metode og verktøy for profilering (Shorthand)

**Comment by thomiz** [comment]
Lukker siden forslag kommer andre veier
