### ISSUE TITLE
Referat møte #1 QA

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#58]
Sjekker dere at det ikke er noe helt feil her 
https://github.com/HL7Norway/best-practice/blob/master/docs/FHIR-faglig-forum/referat/2020-11-04-referat.md

Har du en pdf av presentasjon @kennethmyhra 
Kan gå inn her: https://github.com/HL7Norway/best-practice/tree/master/docs/FHIR-faglig-forum/presentasjon

**Comment by oaassv** [comment]
Ser bra ut.

**Comment by kennethmyhra** [comment]
Presentasjonen er lagt til: b6d2b4a

Referatet ser bra ut!

**Comment by thomiz** [comment]
Takk for det @kennethmyhra

**Comment by rockphotog** [comment]
Tommel opp. Kan sikkert småpynte litt, men siden vi versjonskontrollerer er jo alt transparent. God idé å prøve å få med en god del spørsmål/svar, det bidrar godt til opparbeidelse av kunnskap og best practice.

**Comment by thomiz** [comment]
Takk! Da regner vi den som god nok.

**Comment by rockphotog** [comment]
Kan lenke til Kenneths PDF.
