### ISSUE TITLE
Finne internasjonale namespace for ICD-10/ICPC-2

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/best-practice#6]
Vi anbefaler nå å bruke OID/Volven for disse internasjonale kodeverkene, men vi må finne hva som brukes internasjonalt, på samme måte som SNOMED CT.

**Comment by rockphotog** [comment]
Ikke noe godt svar her, mulig grunnet nasjonale varianter - ikke mulig?
https://www.hl7.org/fhir/terminologies-systems.html

**Comment by rockphotog** [comment]
Se også https://www.hl7.org/fhir/icd.html for ICD-X.

**Comment by rockphotog** [comment]
Norsk OID for ICD-10: 2.16.578.1.12.4.1.1.7110
Norsk OID for ICPC-2: 2.16.578.1.12.4.1.1.7170

Må være med som (alternativ) id i NamingSystem

```
<uniqueId> 
    <type value="oid"/> 
    <value value="2.16.578.1.12.4.1.1.7110"/> 
  </uniqueId> 
```

...muligens med `<preferred value="true"/> `hvis vi ønsker at disse skal trumfe evt. internasjonale, men ikke offisielle, id'er.

**Comment by thomiz** [comment]
Dette er duplikat av sak for [no-basis endringer](https://github.com/HL7Norway/basisprofiler-r4/issues/113)
