### ISSUE TITLE
Forslag: Prinsipp 11 for områdeprofiler

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#63]
Vi ønsker at spesifikasjoner og definisjoner er tilgjengelige og at prosessen rundt utvikling og vedlikehold av områdeprofiler er tilgjengelig og at alle har lik tilgang til oppdaterte spesifikasjoner. Vi får bare til dette om arbeidet med områdeprofiler blir publisert på en åpent tilgjengelig plattform for vedlikehold av kildekode (les GitHub). Foreslår derfor prinsipp 11:

**Prinsipp 11: Områdeprofiler skal utvikles og vedlikeholdes på en åpen plattform**
Kildekoden som definerer conformance og terminology ressursene for områdeprofilen og implementasjonsguiden skal utvikles og vedlikeholdes på en åpen plattform for vedlikehold av kildekode, fortrinnsvis knyttet til HL7 Norge eller HL7 internasjonalt.

**Comment by kennethmyhra** [comment]
Ja, enig når vi snakker om områdeprofiler som er eller skal bli nasjonale

Dette fikk meg til å tenke på eierskap og forvaltningsansvaret til områdeprofilene som havner under HL7 Norge paraplyen. Det burde defineres opp en organisasjon/person med eierskap når man overtar en slik områdeprofil

**Comment by oaassv** [comment]
Enig i at dette er et viktig tema. Kan vi alternativt integrere det i nummer 10, så vi beholder et rundt tall? :). Eierskap og forvaltning er en diskusjon vi også må løfte til Direktoratet. Personlig mener jeg det er problematisk å overlate så sentrale og om ikke lenge potensielt ressurskrevende forvaltning til en organisasjon basert på frivillig innsats. Det finnes per nå en egen folder på HL7 Norge-portalen dedikert til områdeprofiler.

**Comment by thomiz** [comment]
Ja, vi må antakelig jobbe mye i forbindelse med å få på plass robust forvaltning av områdeprofiler som @kennethmyhra påpeker. Noe av koordineringsarbeidet må antakelig gjennomføres av HL7 Norge og Direktoratet for e-helse. Hovedjobben med å forvalte de tekniske profilene får vi forhåpentligvis til med innsats fra hovedansvarlige organisasjoner og community innsats, men her må vi vurdere underveis hva som fungerer best. Jeg tror vi må ha et prinsipp 11 siden prinsipp 10 blir veldig uklart og får for mye innhold hvis vi stlår disse sammen?

**Comment by rockphotog** [comment]
Skal vi legge inn her punktet om leverandør-/løsningsuavhengig?

"_Nasjonale områdeprofiler og implementasjonsguider er løsningsnøytrale. Kildekoden skal utvikles og forvaltes i samarbeid på en åpent tilgjengelig plattform_" (les: GitHub etc.)

**Comment by thomiz** [comment]
Forslag:

> **Prinsipp 11: Områdeprofiler skal utvikles og vedlikeholdes på en åpen plattform**
Nasjonale områdeprofiler og implementasjonsguider er leverandør og løsningsnøytrale. Kildekoden skal utvikles og forvaltes i på en åpent tilgjengelig plattform som gjør det mulig for alle interesserte å komme med innspill til områdeprofilene.

**Comment by rockphotog** [comment]
En til for fredagen:

> **Prinsipp 11: Områdeprofiler skal utvikles og vedlikeholdes åpent**
Nasjonale områdeprofiler og implementasjonsguider er leverandør- og løsningsnøytrale. Kildekoden skal utvikles og forvaltes på en åpent tilgjengelig plattform som gjør det mulig for alle interesserte å delta.

**Comment by oaassv** [comment]
Siste forslag inneholder slik jeg ser det to ulike ting. En del sier noe om at formen skal være leverandøruavhengig, den andre at profilene skal utvikles på en åpen plattform. Er det litt mye for et enkelt prinsipp?

Ellers er også diskusjonen her diskusjonen om hva som gjelder helt generelt for FHIR (og standardiseringsarbeid) og hva som bør inn som prinsipper for områdeprofiler ......

**Comment by thomiz** [comment]
Jeg tenker åpenhet og leverandørnøytralitet godt kan stadfestes i samme prinsipp siden en av måtene vi nettopp sikrer at vi faktisk utvikler leverandør og løsningsnøytrale løsninger er å gjennomføre utvikling og normering på en åpen plattform. Da kan alle se, alle kan kommentere og alle kan engasjere seg og sikre at uheldige bindinger til enkelt løsninger eller leverandører ikke blir en del av det nasjonale arbeidet.

Men er ikke helt uenig i at det ligger implisitt i standardiseringsarbeidet, problemet er at det er implisitt, men vi ønsker kanskje at svært viktige vurderinger blir gjort eksplisitt?

**Comment by oaassv** [comment]
Enig, litt prinsippdiskusjon (om prinsipper:)), løfte  til TSK fredag?
Øyvind 
    På lørdag 6. februar 2021, 22:03:50 CET skrev Thomas Tveit Rosenlund <notifications@github.com> følgende:  
 
 


Jeg tenker åpenhet og leverandørnøytralitet godt kan stadfestes i samme prinsipp siden en av måtene vi nettopp sikrer at vi faktisk utvikler leverandør og løsningsnøytrale løsninger er å gjennomføre utvikling og normering på en åpen plattform. Da kan alle se, alle kan kommentere og alle kan engasjere seg og sikre at uheldige bindinger til enkelt løsninger eller leverandører ikke blir en del av det nasjonale arbeidet.

Men er ikke helt uenig i at det ligger implisitt i standardiseringsarbeidet, problemet er at det er implisitt, men vi ønsker kanskje at svært viktige vurderinger blir gjort eksplisitt?

**Comment by thomiz** [comment]
God ide @oaassv  fint å få disktutert dette i TSK.

**Comment by oaassv** [comment]
Setter det på agendaen

**Comment by thomiz** [comment]
Closes #66

**Comment by thomiz** [comment]
Prinsipp 11 er innarbeidet i dokumentet
