### ISSUE TITLE
Prinsipp om leverandøruavhengige områdeprofiler

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#66]
Vi fikk tilbakemelding på at det bør nedfelles i prinsippene for områdeprofiler at disse må være leverandøruavhengige. Bør dette være et eget prinsipp?

**Comment by cgerno** [comment]
Definitivt! Områdeprofiler skal formes av samfunsbehov i helse med prioriteringen av mest "kroniske"  (kreft, diabetes, etc.) og/eller "akkute" (Covid-19 eller sjenerelt pandemier) interaksjonsdomener. Helseøkonomiskt sett, skal leverandørene spiler en sekundær rolle: er det behove for noe løsninger (etterspørsel), skal leverandørene prøve å by på noe (tilbud).

**Comment by kennethmyhra** [comment]
Ja, 100%. Støtter komment@cgerno over sier

**Comment by oaassv** [comment]
Helt enig i at profilene skal være leverandøruavhengige. Spørsmålet er om det er nødvendig å det som et eget prinsipp eller om vi heller sier at det blir en nødvendig konsekvens av å følge de nåværende prinsippene. Hvis vi følger for eksempel internasjonale IG-er for utforming av profilene så er vi per def leverandøruavhengige. Vi tok det ut av NIKT arkitekturprinsipper for noen år siden av de samme årsakene - ved å følge prinsippene får man leverandøruavhengige løsninger.

**Comment by thomiz** [comment]
Hvilke andre prinsipper er det som gjør det helt tydelig at profilene skal være leverandøruavhengige @oaassv? Profilene vil jo ikke alltid være basert på internasjonale IG'er? 

Jeg tenkte dette kunne være et godt prinsipp på linje med at profilene skal være mest mulig uavhengige av samhandlingsform?

**Comment by oaassv** [comment]
Jeg tenker et alteranativ kunne være at leverandøruavhengighet kan presiseres for å beskrive formålet med prinsippene. Vi snakker om at både basis- og områdeprofiler skal være gjenbrukbare profiler på nasjonalt nivå. Da er implisitt et av hovedformålene at profilene skal være leverandøravhengige. 
Jeg synes en god del av argumentasjonen vi brukt for å ta ut leverandøruavhengighet i revisjonen av NIKTs arkitekturprinsipper også gjelder her. Men hvis det er stemning for det kan det eventuelt tas med for tydeliggjøringens skyld.

**Comment by thomiz** [comment]
Jeg mener også dette er implisitt av formålet med nasjonale profiler, tenker mest i forhold til tydelighet og siden det (forhåpentligvis) er mange som skal arbeide med dette er det kanskje en fordel å være mer eksplisitt.

**Comment by rockphotog** [comment]
Jeg mener det ligger i naturen til en standard at den er nøytral. Om ikke som et *tekstlig* prinsipp, så kan vi beskrive det et passende sted og/eller skrive en introduksjon til normering/standardisering. Gjerne uavhengig av FHIR om mulig, tror vi har nok materiale å ta av.

**Comment by thomiz** [comment]
Jeg er nok uenig i dette. Jeg kan ikke se at bruk av en internasjonale standarder i seg selv og spesielt ikke i utviklingen av områdeprofiler vil i sin natur være leverandørnøytral.

Strategien er at leverandører og prosjekter gjennom tilpasning av standarden skal presisere hvordan den skal benyttes innen forskjellige anvendelser. Jeg som leverandør kan godt ta utgangspunkt i HL7 FHIR og lage noen "områdeprofiler" som er spesielt tilpasset meg som leverandør og legge inn tekniske krav som stammer fra mine produkter, som vil gjøre profilene ubrukelige for alle andre leverandører. Vi får bare håpe at de kvalitetssikring og forankringsrutinene som ligger i metoden for utvikling av områdeprofiler vil føre til at slike tilpasninger tas bort fra områdeprofilene. Nettopp derfor tror jeg det er verdifullt at dette blir nedfelt som et prinsipp for områdeprofiler, fordi arbeidet med disse i hovedsak skal styres av mange ulike prosjekter og leverandører som bevisst eller ubevisst kan nedfelle leverandørspesifikke krav i profilene. Områdeprofilene må kvalitetssikres, og da spesielt opp mot de nedfelte prinsippene for disse.

**Comment by kennethmyhra** [comment]
Enig med Thomas sitt utsagn. Vi har hatt flere dialoger der begrensinger eller utfordringer av teknisk art smitter over i profilene.

**Comment by rockphotog** [comment]
Med standard her mente jeg egentlig (normert) nasjonal områdeprofil. Målet er at det skal normeres av Direktoratet for e-helse, så det er den tradisjonen jeg har i bakhodet. Tror ikke vi er uenige om noe som helst her. 

Kvalitetssikringen skal fjerne avhengigheter. Vi må dog holde tunga rett i munnen når vi ser på spisset vs generell. Hvor grensen går vil ikke alltid være like tydelig. Vi må se for oss en slags 80/20-regel (som fortsatt betyr at profilen er 100% brukbar ut av boksen for de aller fleste). 

Vi kan gjerne ha et prinsipp, men vi bør se på definisjonen av nasjonale områdeprofiler så det ikke er stor tvil om hva det er (og ikke er).

**Comment by thomiz** [comment]
Se #63

**Comment by thomiz** [comment]
Lagt til prinsipp 11 i endelig versjon
