### ISSUE TITLE
Prinsipp 7: Skrive om (områdeprofiler)

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#68]
Prinsipp 7: En områdeprofil skal benytte must-support for elementer
Must-support betyr at fagsystemer skal støtte og kunne behandle informasjon for disse elementene. Den enkelte implementasjonsguide bør spesifikt beskrive hvilke krav som følger av must-support. Ulike anvendelser kan ha ulike krav til must-support-elementer. 

Kommentar fra Espen: Nesten som en oppfordring all tid vi ønsker best practice – kanskje kutte den?
Enige om å skrive litt om. Det er viktig at vi får frem at IG må dokumenterer hvordan must-support benyttes og tar stilling til hvilke elementer som skal ha must-support.

**Comment by rockphotog** [comment]
Teksten er min omskriving/forslag, så kommentaren fra meg er litt misvisende. Tror det er en setning jeg foreslo fjernet, altså ikke prinsippet - mulig den siste setningen.

Vi trenger kanskje en kort forklaring på hvorfor vi foretrekker must-support når et felt må støttes, og hvordan dette er forskjellig fra obligatorisk ved bruk av kardinalitet 1..n.

**Comment by rockphotog** [comment]
Til info, her ligger tekst for prinsipp 7 som uansett må omskrives, og nå ikke er det samme som foreslås:
https://hl7norway.github.io/best-practice/docs/no-national-profiles-principles.html

**Comment by thomiz** [comment]
Det lå feil tekst i branchen. Jeg har korrigert til det vi hadde kommentarrunde på 12. mars i branchen:
https://github.com/HL7Norway/best-practice/blob/metode-omr%C3%A5deprofiler-v1/docs/no-domain-metode/no-national-profiles-principles.md

@rockphotog tar d QA og lukker denne

**Comment by rockphotog** [comment]
Ser fint ut.
