### ISSUE TITLE
JSON og/eller XML - Beste praksis

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/best-practice#69]
Bakgrunn er en problemstilling som har havnet på pulten min: En tjeneste velger kun ett av formatene, som kan skape utfordringer for en klient. 

[Serialization Format Representations](http://hl7.org/fhir/formats.html#wire)
> Clients and servers can **choose** what syntax(s) to implement. _**In the interests of interoperability, servers SHOULD support both the XML and JSON formats**_, which have the same functionality, for different technical stacks. 

(Mine uthevinger). 

Det er en falsk balanse her, da klienten er avhengig av kapabilitetene til tjeneren. 

- Bør vi understreke viktigheten av å støtte _både_ JSON og XML for tjenere? 
- Kan det holde som beste praksis, eller må det normeres (retningslinjer -> obligatorisk standard)?
- Bør det gjelde alle, eller spesielt for noen (som sentrale komponenter)?
- Hva med dokumenter?

**Comment by thomiz** [comment]
Er ikke dette nok?
https://www.hl7.org/fhir/formats.html#wire

**Comment by rockphotog** [comment]
Det er den jeg både siterer og lenker til, ja, så det hjelper meg lite med problemstillingen.

**Comment by oaassv** [comment]
Enig i at det er et poeng at servere støtter begge formater. Har vi noe oversikt over hva som er praksis i dagens implementasjoner i Norge?

**Comment by rockphotog** [comment]
Tror ikke det, hadde vært interessant (og overkommelig). 

Problemstillingen jeg har på bordet er litt annerledes enn jeg først trodde (og egentlig verre...), så det er ikke noe hast, men noe vi bør ha i bakhodet.

**Comment by thomiz** [comment]
Men hvorfor er ikke det som står i standarden nok? Vil beste praksis i Norge hvor vi i prinsippet må skrive det samme som i HL7 FHIR gi noen merverdi?

> SHOULD/SHOULD NOT: A best practice or recommendation to be considered by implementers within the context of their particular implementation; there may be valid reasons to ignore an item, but the full implications must be understood and carefully weighed before choosing a different course

Så lenge alle forholder seg til denne delen av standarden så er jo egentlig problemet løst. Det står jo i indirekte at du skal ha veldig gode grunner for IKKE å støtte både JSON og XML når du lager en FHIR tjener. Har aldri oppfattet at det har vært noe problem. Klienter kan forsåvidt velge, men bør uansett undersøke CapabilityStatement. Synes ikke vi skal gjøre noe mer her enn å i høyden klargjøre forventningene om å følge standarden på dette punktet, spesielt for tjenester som er offentlig tilgjengelig (internt i en organisasjon kan du gjøre hva du vil egentlig). Men jeg har ikke sett det konkrete problemet du er presentert @rockphotog 

Hvis det viser seg at det faktisk blir et problem må vi stramme inn, helst gjennom arbeid i HL7 international. Dette er aspekter ved bruk av HL7 FHIR som egentlig ikke har noe i nasjonale retningslinjer å gjøre slik jeg ser det.

**Comment by rockphotog** [comment]
> Synes ikke vi skal gjøre noe mer her enn å i høyden klargjøre forventningene om å følge standarden på dette punktet, spesielt for tjenester som er offentlig tilgjengelig

Jeg foreslår egentlig ingen ting. Det er jo nettopp det jeg spør om i OP.

Jeg tar sorgene på forskudd hvis jeg ser humper på veien. Men vi kan gjerne sitte stille i båten på denne.

**Comment by kennethmyhra** [comment]
Må si meg enig med Thomas. Det burde være godt nok det som står i FHIR-standarden. Og dersom man gjør et slikt valg på en server så må man være bevisst på utfordringer det kan skape for forskjellige teknologi-stacker hos klientene. Se min uthevning under.

>Clients and servers can choose what syntax(s) to implement. In the interests of interoperability, servers SHOULD support both the XML and JSON formats, which have the same functionality, **for different technical stacks**.

**Comment by thomiz** [comment]
Jeg tolker dette som fravær av motstand :-) og lukker
