### ISSUE TITLE
QA av bestilling presentasjoner

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#72]
Har laget et forslag til bestillling/talepunkter for presentasjoner til FFF, den trenger QA:
[Bestilling og talepunkter](https://github.com/HL7Norway/best-practice/blob/master/docs/FHIR-faglig-forum/planlegging/Presentasjoner%20FHIR%20fagforum.md)

**Comment by rockphotog** [comment]
Gjort noen tekstlige endringer. 

"Bestilling" og "Talepunkter" tror jeg vi kan slå sammen. Læringspunkter er også litt spredd, vi kan redigere det til ett tema. 
Forvaltningsmodellen er vel mest aktuell hvis det er snakk om områdeprofiler og lignende, den kan vi lenke til etter hvert når vi får opp metoden på wiki. 

Denne tror jeg vi kan fjerne: 
* Begrunnelsen for å benytte HL7 FHIR

**Comment by thomiz** [comment]
Enig i det du skriver @rockphotog

**Comment by thomiz** [comment]
@oaassv og Michal Cermak, kan dere ta en gjennomgang?

**Comment by oaassv** [comment]
Ser bra ut!
