### ISSUE TITLE
Planlegge Møte 5 FHIR fagforum 2021-04-21

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#75]
Tema: Møte 5 SMART on FHIR

- [x] Kalle inn planleggingsmøte
- [x] Agenda
- [x] Innledere
- [x] Følge opp presentasjoner
- [x] Innkalling
- [x] Kommunikasjon
   - [x] info@hl7.no
   - [x] Linkedin
   - [x] Workplace
- [x] Påminnelse
- [x] Presentasjon og agenda til møtet
- [x] Opprette skjelett til referat

**Comment by rockphotog** [comment]
Studentene som har jobbet med DIPS/NAV er en kandidat:
https://www.dips.com/no/studenter-lager-smart-fhir-integrasjon-mellom-dips-og-nav

**Comment by thomiz** [comment]
Innledere?
Hva skal skille dette fra webinaret?
Basic intro til SMART + noen mer avanserte tema?
Oppfølging fra planleggingsmøte:

## Foreløpig agenda

* Konsept SMART Lars @rockphotog 
   * Kanskje noe rundt arkitektur, grunnmur som skal støtte opp om dette?
* Teori app launch framework @kennethmyhra 

* @kennethmyhra spør om Førrerrett leverandøren, som har implementert @kennethmyhra 
   * Leverandør og implementasjonserfaring noen som har laget noe er viktig å få tak i

## Andre leads

* Noen på Sørlandet har visst implementert
* Bulk data Belika
* Sjekk med Egde og sørlandsmiljøet @thomiz 
* DIPS Thor Stenbæk/ studentene er kanskje en mulighet @rockphotog 
* Snakk med Øystein Nytrø om han har noen konkrete implementasjoner å vise @thomiz 

## Forberede gode spørsmål

* Tenk på noen spørsmål rundt HelseID og felles tillitstjenester. API management spørsmål?

## Hovedmål med SMART FFF

Vise at dette ikke er teori, men fungerer også i praksis!

**Comment by thomiz** [comment]
Lars Kristian har takket ja til innledningsforedrag.

**Comment by thomiz** [comment]
KJ API er ikke modent for presentasjon på nåværende tidspunkt, kjenner ikke til at eksterne har integrert mot det.

**Comment by thomiz** [comment]
DIPS/Thor Stenbæk har takket ja

**Comment by thomiz** [comment]
@kennethmyhra sjekker Aspit

Øyvind kan ta et 5 minutter fra HL7 Norge 
* om profileringsworkshop
* WGM early bird starten av mai
* Metoden for områdeprofilering publisert på GitHub og e-helse 

@thomiz skriver ferdig agendaen når Aspit er bekreftet og sender ut invitasjon i henhold til kommunikasjonsplan

**Comment by thomiz** [comment]
Innspill til agendaen @rockphotog @kennethmyhra @oaassv @micer2004 ?

https://github.com/HL7Norway/best-practice/blob/master/docs/FHIR-faglig-forum/agenda/2021-04-21-agenda.md

**Comment by rockphotog** [comment]
Møte med Thor/DIPS, Kenneth og undertegnede gjennomført - dette blir spennende.
