### ISSUE TITLE
Siste QA før publisering metode områdeprofiler

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#80]
- [x] Thomas innarbeider endringer etter kommentarrunden (2021-25-03)
- [x] @rockphotog siste QA av teksten (frist 2021-04-06)
- [x] @thomiz siste QA av teksten (frist 2021-04-06)
- [x] @gryseland siste QA av teksten (frist 2021-04-06)
- [x] Gry synkroniserer sine endringer inn i siste versjon
- [x] @thomiz pull request #77 
- [x] @gryseland publiserer e-helse
- [x] pdf virker ikke @gryseland 
- [x] Lenker må sjekkes @gryseland 
- [x] @thomiz - legg inn lenker i andre avsnitt (strategi og veikart) kan du se på referansene i avsnitt to? https://github.com/HL7Norway/best-practice/blob/metode-omr%C3%A5deprofiler-v1/docs/no-domain-metode/bakgrunn.md

**Comment by thomiz** [comment]
@gryseland jobber med synkroniseringen

Noen forskjellige nivå på e-helse.no, det er OK
Ny mal på e-helse.no, kom i dag.

**Comment by thomiz** [comment]
Er det noen referanser i avsnitt2?
* kan du se på referansene i avsnitt to? https://github.com/HL7Norway/best-practice/blob/metode-omr%C3%A5deprofiler-v1/docs/no-domain-metode/bakgrunn.md

**Comment by rockphotog** [comment]
Alle lenkene peker til fungerende sider, hvis det var det du tenkte på, @thomiz

**Comment by thomiz** [comment]
Jeg vet ikke hva jeg tenkte på med den kommentaren, håpet noen av der husket det @rockphotog

**Comment by rockphotog** [comment]
Kanskje sjekk mot rapporten fra 2020?

**Comment by thomiz** [comment]
Levert
