### ISSUE TITLE
Møte 9 FHIR Fagforum

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/best-practice#94]
- [x] Innkalling
- [x] Kalle inn planleggingsmøte
- [x] Agenda
- [x] Innledere
- [x] Følge opp presentasjoner
- [x] Kommunikasjon
   - [x] info@hl7.no
   - [x] Linkedin
   - [x] Workplace
- [x] Påminnelse
- [x] Presentasjon og agenda til møtet
- [x] Opprette skjelett til referat

**Comment by thomiz** [comment]
Tema Desember innspill:
DIPS og NAV om SMART implementasjon med demo, kontakt Thor

**Comment by thomiz** [comment]
* Sendte til NILAR, igår
* Har ikke fått noen tilbakemelding på generell invitasjon.

**Comment by rockphotog** [comment]
Sendt til DIPS i dag, noe forsinket fra meg...

**Comment by thomiz** [comment]
* Andre PR fremstøt?
* NHN skulle gjøre en kartlegging, divisjonsdirektør sier at det ikke alltid er hensiktsmessig?
* Melde.no - AdverseEvent
* Dødsmelding - prosjektet Patient og Questionnaire, QuestionnaireResponse, kanskje ikke klar senere?
  * Tidlig fase
* NILAR - "trenger" FHIR til finmasket søk
* CareTeam og Task - digital dialog HelseNorge innbyggerportalen
  * Frank Bråthen fra NHN inn på presentasjonssiden sammen med HSØ @oaassv 
* AuditEvent eventuelt over jul

Kahoot

*

**Comment by thomiz** [comment]
@oaassv Tar kontakt med leverandør om presentasjon av prosjekt

**Comment by oaassv** [comment]
Ledidi stiller med 20 min presentasjon om hvordan de bruker FHIR.
Øyvind 
    På torsdag 11. november 2021, 15:15:24 CET skrev Thomas Tveit Rosenlund ***@***.***> følgende:  
 
 


@oaassv Tar kontakt med leverandør om presentasjon av prosjekt

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thomiz** [comment]
Tema og presentatør fra Ledidi @oaassv 
Følge opp NILAR prosjektet om presentasjon @thomiz 

@thomiz kaller inn til møter frem til sommeren (3 møter før sommeren)
* samarbeidsmøte med HL7 Norge - fysisk oppmøte med bevertning
* Sponsorpenger?

## Møteplan 2022

Legemidler og  medikasjon til januar/februar?
SAFEST - medikasjon som tema 
* SFM er kanskje i drift

Hvordan fungerer HL7 organisasjonen?
+ eventuelt et arkitekturtema

Terminologi on FHIR juni 2022

**Comment by thomiz** [comment]
Møte med Ledidi:
Løsningen  integrert database og skjemadefinisjon, statistikk og datapresentasjon
* GDPR og Schrems2
* ENISA kom med nye retningslinjer for Schrems2 (september)
  * Kan løse en god del av Schrems2 teknisk
* Azure skal implementere dette de også, men Amazon er kommet litt lenger i forhold til dette
* Confidential computing implementasjon hos  Amazon er langt fremme
* Konfidential prosessering,
* Demo av løsningen
* Interoperabilitet - inn og ut av systemet
  * Template klar for FHIR baserte datasett
  * Variabel definisjon - kan være basert på HL7 FHIR
  * Definiere transformasjon til variablene
  * SNOMED vs FHIR i denne forbindelse - terminologi /ontologi vs informasjonsmodeller
* Hvem i HAP - ?
